@host = http://localhost:3000

###
GET {{host}}/users HTTP/1.1

###
POST {{host}}/user HTTP/1.1
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "teste",
  "enabled": true
}

###
PATCH {{host}}/user/3 HTTP/1.1
Content-Type: application/json

{
  "name": "Teste2 Atualizado",
  "email": "atualizado@teste.com",
  "password": "novasenha"
}

###
DELETE {{host}}/user/3 HTTP/1.1
