### CREATE A USER
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "testd name",
    "email": "teste@teste.com",
    "password": "teste"
}

### UPDATE A USER
PATCH http://localhost:3000/user/3 HTTP/1.1
content-type: application/json

{
    "name": "atualizado",
    "email": "atualizado@teste.com",
    "password": "testeupdate",
    "enabled": false
}

### DELETE A USER
DELETE http://localhost:3000/user/1 HTTP/1.1

### ENABLE A USER
PATCH http://localhost:3000/user/3 HTTP/1.1
content-type: application/json

{
    "enabled": true
}
