services:

  postgres:
    image: postgres:14-alpine
    restart: on-failure:3
    volumes:
      - ./src/infra/db/pg-promise/init.sql:/db/scripts/init.sql
      - ./src/infra/db/pg-promise/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: on-failure:3
    links:
      - postgres
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
