# =====
# build
FROM node:20-buster AS builder

WORKDIR /home/node/app

ARG POSTGRES_HOSTNAME
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG POSTGRES_DBNAME
ARG PRIVATE_KEY
ARG REFRESH_PRIVATE_KEY
ARG CLOUDINARY_APIKEY
ARG CLOUDINARY_APISECRET
ARG CLOUDINARY_CLOUDNAME
ARG CLOUDINARY_FOLDER
ARG CLOUDINARY_URL
ARG SMTP_PASSWORD
ARG SMTP_SECURE
ARG SMTP_SERVER_ADDRESS
ARG SMTP_SERVER_PORT
ARG SMTP_USERNAME

ENV POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_DBNAME=${POSTGRES_DBNAME}
ENV PRIVATE_KEY=${PRIVATE_KEY}
ENV REFRESH_PRIVATE_KEY=${REFRESH_PRIVATE_KEY}
ENV CLOUDINARY_APIKEY=${CLOUDINARY_APIKEY}
ENV CLOUDINARY_APISECRET=${CLOUDINARY_APISECRET}
ENV CLOUDINARY_CLOUDNAME=${CLOUDINARY_CLOUDNAME}
ENV CLOUDINARY_FOLDER=${CLOUDINARY_FOLDER}
ENV CLOUDINARY_URL=${CLOUDINARY_URL}
ENV SMTP_PASSWORD=${SMTP_PASSWORD}
ENV SMTP_SECURE=${SMTP_SECURE}
ENV SMTP_SERVER_ADDRESS=${SMTP_SERVER_ADDRESS}
ENV SMTP_SERVER_PORT=${SMTP_SERVER_PORT}
ENV SMTP_USERNAME=${SMTP_USERNAME}

RUN apt update && \
  apt install git -y && \
  git clone https://github.com/ikatoo/backend.git . && \
  npm install

CMD npm run start:dev
