name: Build Container

on:
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Authenticate on Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Build Container
        run: docker build --tag ikatoo-backend:${{ github.ref_name }} .

      - name: Push Container
        run: |
          docker push ghcr.io/${{ github.repository }}/ikatoo-backend:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/ikatoo-backend:${{ github.sha }}
