name: Build Container

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Authenticate on Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHP_TOKEN }}

      - name: Build Container
        run: docker build --tag ghcr.io/${{ github.repository }}/ikatoo-backend:${{ github.ref_name }} .

      - name: Push Container
        run: docker images && echo "github.ref_name = ${{ github.ref_name }}"
        # run: docker push ghcr.io/${{ github.repository }}/ikatoo-backend:${{ github.ref_name }}
