name: Tests Workflow on Push
on: [push, workflow_dispatch]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        node: [18]
    env:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DBNAME: postgres
      PRIVATE_KEY: valid-private-key

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      psql:
        image: postgres
        links:
          - postgres
        volumes:
          - ./src/infra/db/pg-promise/scripts:/db/scripts
        env:
          POSTGRES_PASSWORD: postgres
        command: psql -v ON_ERROR_STOP=1 -h postgres --username postgres --dbname postgres -a -f /db/scripts/init.sql

    container:
      image: postgres:14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Create Tables
        env:
          PGPASSWORD: postgres
        run: psql -v ON_ERROR_STOP=1 --host postgres --username postgres --dbname postgres -a -f src/infra/db/pg-promise/init.sql

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Nest Unit Tests
        run: npm run test
      
      - name: Send email when fail tests
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: mckatoo@outlook.com
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Failed tests
          to: mckatoo@gmail.com
          from: iKatoo Repository
          html_body: Tests of the repository <a href="https://github.com/${{github.repository}}/tree/${{github.ref_name}}">${{github.repository}}</a> if failed. Please, verify and fix de code.
