name: Tests Workflow on Pull Request
on: pull_request

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: node:18
    env:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DBNAME: postgres
      PRIVATE_KEY: valid-private-key

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      psql:
        image: postgres
        volumes:
          - ./src/infra/db/pg-promise/scripts:/db/scripts
        command: psql --host postgres --username postgres --dbname postgres -a -f /db/scripts/init.sql


    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: npm ci

      - name: Nest Unit Tests
        run: npm run test:e2e
      
      - name: Send email when fail tests
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: mckatoo@outlook.com
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Failed tests
          to: mckatoo@gmail.com
          from: iKatoo Repository
          html_body: Tests of the repository <a href="https://github.com/${{github.repository}}/tree/${{github.ref_name}}">${{github.repository}}</a> if failed. Please, verify and fix de code.
